olist_dbt: #my_project
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dbt-project-454118
      dataset: dev
      threads: 1
      keyfile: "C:\\Users\\Lenovo\\Downloads\\dbt-project-454118-95aa1a7bcf92.json"

  target: dev

#    dev:
#      type: duckdb
#      threads: 1
#      path: "olist.duckdb"
#      schema: dev
#
#    prod:
#      type: duckdb
#      threads: 1
#      path: "olist.duckdb"
#      schema: prod