olist_dbt: #my_project
  outputs:
    dev:
      type: duckdb
      threads: 1
      path: "olist.duckdb"
      schema: dev

    prod:
      type: duckdb
      threads: 1
      path: "olist.duckdb"
      schema: prod

  target: dev