version: 2

sources:
  - name: olist_data
    database: olist
    schema: olist_data
    tables:
      - name: customers  # The customers table I will reference
        description: "This dataset contains customer and location information. Each order is assigned a unique customer_id, so the same customer gets different IDs for each order. The customer_unique_id helps identify customers who made repeat purchases, preventing the appearance of separate customers for each order."
        columns:
          - name: customer_id
            description: "Key to the orders dataset. Each order has a unique customer_id."

          - name: customer_unique_id
            description: "Unique identifier of a customer. Allowing the tracking of repeated purchases."

          - name: customer_zip_code_prefix
            description: "The first five digits of the customers zip code."

          - name: customer_city
            description: "The city where the customer is located."

          - name: customer_state
            description: "The abbreviated state where the customer is located."

      - name: geolocation
        description: "This dataset has information on Brazilian zip codes and its lat/lng coordinates."
        columns:
          - name: geolocation_zip_code_prefix
            description: "The first five digits of the zip code for the location."

          - name: geolocation_lat
            description: "Latitude coordinate of the location."

          - name: geolocation_lng
            description: "Longitude coordinate of the location."

          - name: geolocation_city
            description: "City name of the location."

          - name: geolocation_state
            description: "State abbreviation of the location."

      - name: order_items
        description: "This dataset includes data about the items purchased within each order."
        columns:
          - name: order_id
            description: "Unique identifier for each order."

          - name: order_item_id
            description: "Sequential number identifying for items within an order because orders can have multiple items."

          - name: product_id
            description: "Identifier for the purchased product."

          - name: seller_id
            description: "Identifier for the seller."

          - name: shipping_limit_date
            description: "Deadline (timestamp) for the seller to ship the product."

          - name: price
            description: "Price of the product item."

          - name: freight_value
            description: "Shipping cost associated with the product item. If an order contains multiple items, the freight cost is divided among the items."

      - name: order_payments
        description: "This dataset includes data about the orders payment options."
        columns:
          - name: order_id
            description: "Unique identifier for the order."

          - name: payment_sequential
            description: "Sequence number of the payment within an order. A customer may pay an order with more than one payment method."

          - name: payment_type
            description: "Payment method (example: credit_card, voucher, etc)."

          - name: payment_installments
            description: "Number of installments chosen for the payment."

          - name: payment_value
            description: "Amount paid for the order."

      - name: order_reviews
        description: "This dataset includes data about the reviews made by the customers."
        columns:
          - name: review_id
            description: "Unique identifier for each review."

          - name: order_id
            description: "Identifier for the associated order."

          - name: review_score
            description: "Rating given by the customer (1 to 5)"

          - name: review_comment_title
            description: "Title of the review comment."

          - name: review_comment_message
            description: "Detailed review message."

          - name: review_creation_date
            description: "Timestamp in which the satisfaction survey was sent to the customer."

          - name: review_answer_timestamp
            description: "Timestamp when the satisfaction survey was responded."

      - name: orders
        description: "This is the core dataset. From each order you might find all other information."
        columns:
          - name: order_id
            description: "Unique identifier for each order."

          - name: customer_id
            description: "Identifier for the customer who placed the order. Each order has a unique customer_id."

          - name: order_status
            description: "Status of the order (example: delivered, canceled, etc)."

          - name: order_purchase_timestamp
            description: "Timestamp when the order was purchased."

          - name: order_approved_at
            description: "Timestamp when the order/payment was approved."

          - name: order_delivered_carrier_date
            description: "Timestamp when the order was handed to the carrier / logistic partner."

          - name: order_delivered_customer_date
            description: "Timestamp when the order was delivered to the customer."

          - name: order_estimated_delivery_date
            description: "Estimated delivery date of the order at the purchase moment."

      - name: products
        description: "This dataset includes data about the products sold by Olist."

      - name: sellers
        description: "This dataset includes data about the sellers that fulfilled orders made at Olist."

      - name: product_category_name_translation
        description: "This dataset includes the english translation of the product_category_name."